config:
  exposedMethods:
    Call: SimpleService::call
    Compare: SimpleService::compare
    DeliberateDiffNoop: SimpleService::sillyNoop
    EchoBinary: SecondService::echoBinary
    EchoBool: SecondService::echoBool
    EchoDouble: SecondService::echoDouble
    EchoEnum: SecondService::echoEnum
    EchoI16: SecondService::echoI16
    EchoI32: SecondService::echoI32
    EchoI64: SecondService::echoI64
    EchoI8: SecondService::echoI8
    EchoString: SecondService::echoString
    EchoStringList: SecondService::echoStringList
    EchoStringMap: SecondService::echoStringMap
    EchoStringSet: SecondService::echoStringSet
    EchoStructList: SecondService::echoStructList
    EchoStructSet: SecondService::echoStructSet
    EchoTypedef: SecondService::echoTypedef
    GetProfile: SimpleService::getProfile
    HeaderSchema: SimpleService::headerSchema
    Ping: SimpleService::ping
    TestUUID: SimpleService::testUuid
    Trans: SimpleService::trans
    TransHeaders: SimpleService::transHeaders
    TransHeadersNoReq: SimpleService::transHeadersNoReq
    TransHeadersType: SimpleService::transHeadersType
    URLTest: SimpleService::urlTest
  idlFile: clients/baz/baz.thrift
  idlFileSha: '{{placeholder}}'
  genTestServer: true
name: baz
type: tchannel
