// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  bar

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( BarException ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BarException ) UnmarshalJSON([]byte) error { return nil }
func ( BarException ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BarException ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BarException *BarException

func ( BarRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BarRequest ) UnmarshalJSON([]byte) error { return nil }
func ( BarRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BarRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BarRequest *BarRequest

func ( BarResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BarResponse ) UnmarshalJSON([]byte) error { return nil }
func ( BarResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BarResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BarResponse *BarResponse
