// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package health

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson11da19ddDecodeGithubComUberZanzibarExamplesExampleGatewayEndpointsHealth(in *jlexer.Lexer, out *JSONResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ok":
			out.Ok = bool(in.Bool())
		case "message":
			out.Message = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson11da19ddEncodeGithubComUberZanzibarExamplesExampleGatewayEndpointsHealth(out *jwriter.Writer, in JSONResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"ok\":")
	out.Bool(bool(in.Ok))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"message\":")
	out.String(string(in.Message))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v JSONResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson11da19ddEncodeGithubComUberZanzibarExamplesExampleGatewayEndpointsHealth(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v JSONResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson11da19ddEncodeGithubComUberZanzibarExamplesExampleGatewayEndpointsHealth(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *JSONResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson11da19ddDecodeGithubComUberZanzibarExamplesExampleGatewayEndpointsHealth(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *JSONResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson11da19ddDecodeGithubComUberZanzibarExamplesExampleGatewayEndpointsHealth(l, v)
}
