annotationPrefix: zanzibar
clientConfig: ./clients
copyrightHeader: ./copyright_header.txt
endpointConfig: ./endpoints
genCodePackage:
  .thrift: github.com/uber/zanzibar/examples/selective-gateway/build/gen-code
  .proto: github.com/uber/zanzibar/examples/selective-gateway/build/proto-gen
genMock: true
middlewareConfig: ./middlewares
defaultMiddlewareConfig: ./middlewares/default
packageRoot: github.com/uber/zanzibar/examples/selective-gateway
targetGenDir: ./build
idlRootDir: ./idl
moduleIdlSubDir:
  endpoints: .
  default: .
traceKey: x-trace-id
moduleSearchPaths:
  client:
    - clients/*
    - app/*/clients/*
  middleware:
    - middlewares/*
    - middlewares/default/*
  endpoint:
    - endpoints/*
    - endpoints/tchannel/*
    - app/*/endpoints/*
  service:
    - services/*
    - app/*/services/*

