name: echo
type: grpc
config:
  idlFile: clients/echo/echo.proto
  exposedMethods:
    "EchoEcho": "Echo::Echo"
CustomInitialisation: true
CustomImportPath: github.com/uber/zanzibar/v2/examples/example-gateway/clients/echo
