config:
  customImportPath: github.com/uber/zanzibar/v1/examples/example-gateway/clients/quux
  fixture:
    importPath: github.com/uber/zanzibar/v1/examples/example-gateway/clients/quux/fixture
    scenarios:
      EchoMessage:
      - success
      EchoString:
      - success
  customInterface: IClient
dependencies: {}
name: quux
type: custom
