config:
  customImportPath: github.com/uber/zanzibar/v2/examples/example-gateway/clients/quux
  fixture:
    importPath: github.com/uber/zanzibar/v2/examples/example-gateway/clients/quux/fixture
    scenarios:
      EchoMessage:
      - success
      EchoString:
      - success
  customInterface: IClient
dependencies: {}
name: quux
type: custom
CustomInitialisation: false
CustomImportPath: github.com/uber/zanzibar/v2/examples/example-gateway/clients/quux
