// Code generated by zanzibar
// @generated

package bar_test

import (
	"bytes"
	"net/http"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/uber/zanzibar/examples/example-gateway/config"
	"github.com/uber/zanzibar/test/lib/test_gateway"
)

// TODO(zw): benchBytes should be generated according to request type.
var benchBytesForMissingArg = []byte("{}")

func TestMissingArgOKResponse(t *testing.T) {
	var counter int = 0

	config := &config.Config{}
	gateway, err := testGateway.CreateGateway(t, config, nil)
	if !assert.NoError(t, err, "got bootstrap err") {
		return
	}
	defer gateway.Close()

	fakeMissingArg := func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(200)
		// TODO(zw): generate client response.
		if _, err := w.Write([]byte("{}")); err != nil {
			t.Fatal("can't write fake response")
		}
		counter++
	}
	gateway.Backends()["Bar"].HandleFunc(
		"GET", "/missing-arg-path", fakeMissingArg,
	)

	res, err := gateway.MakeRequest(
		"GET", "/bar/missing-arg-path", bytes.NewReader(benchBytesForMissingArg),
	)
	if !assert.NoError(t, err, "got http error") {
		return
	}

	assert.Equal(t, "200 OK", res.Status)
	assert.Equal(t, 1, counter)
}
