// Code generated by zanzibar
// @generated

package bar_test

import (
	"bytes"
	"net/http"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/uber/zanzibar/examples/example-gateway/config"
	"github.com/uber/zanzibar/test/lib/test_gateway"
)

// TODO(zw): benchBytes should be generated according to request type.
var benchBytesForTooManyArgs = []byte("{}")

func TestTooManyArgsOKResponse(t *testing.T) {
	var counter int = 0

	config := &config.Config{}
	gateway, err := testGateway.CreateGateway(t, config, nil)
	if !assert.NoError(t, err, "got bootstrap err") {
		return
	}
	defer gateway.Close()

	fakeTooManyArgs := func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(200)
		// TODO(zw): generate client response.
		if _, err := w.Write([]byte("{}")); err != nil {
			t.Fatal("can't write fake response")
		}
		counter++
	}
	gateway.Backends()["Bar"].HandleFunc(
		"POST", "/too-many-args-path", fakeTooManyArgs,
	)

	res, err := gateway.MakeRequest(
		"POST", "/bar/too-many-args-path", bytes.NewReader(benchBytesForTooManyArgs),
	)
	if !assert.NoError(t, err, "got http error") {
		return
	}

	assert.Equal(t, "200 OK", res.Status)
	assert.Equal(t, 1, counter)
}
