config:
  path: github.com/uber/zanzibar/v2/examples/example-gateway/invalid-path/example
  schema: ./middlewares/example/example_schema.json
dependencies:
  client:
  - baz
  - echo
name: example
type: custom
CustomInitialisation: false
