annotationPrefix: zanzibar
clientConfig: ./clients
copyrightHeader: ./copyright_header.txt
endpointConfig: ./endpoints
genCodePackage: github.com/uber/zanzibar/examples/example-gateway/build/gen-code
genMock: true
middlewareConfig: ./middlewares
mandatoryMiddlewareConfig: ./middlewares/mandatory
packageRoot: github.com/uber/zanzibar/examples/example-gateway
targetGenDir: ./build
thriftRootDir: ./idl
traceKey: x-trace-id
