// Code generated by zanzibar
// @generated

package googlenowClient

// AddCredentialsHTTPRequest is the http body type for endpoint addCredentials.
type AddCredentialsHTTPRequest struct {
	AuthCode string
}
