// Code generated by zanzibar
// @generated

package barClient

import (
	"runtime"

	clients_bar_bar "github.com/uber/zanzibar/examples/example-gateway/build/gen-code/github.com/uber/zanzibar/clients/bar/bar"
	clients_foo_foo "github.com/uber/zanzibar/examples/example-gateway/build/gen-code/github.com/uber/zanzibar/clients/foo/foo"
	"github.com/uber/zanzibar/runtime"
)

func getDirName() string {
	_, file, _, _ := runtime.Caller(0)
	return zanzibar.GetDirnameFromRuntimeCaller(file)
}

// ArgNotStructHTTPRequest is the http body type for endpoint argNotStruct.
type ArgNotStructHTTPRequest struct {
	Request string
}

// NormalHTTPRequest is the http body type for endpoint normal.
type NormalHTTPRequest struct {
	Request *clients_bar_bar.BarRequest
}

// TooManyArgsHTTPRequest is the http body type for endpoint tooManyArgs.
type TooManyArgsHTTPRequest struct {
	Request *clients_bar_bar.BarRequest
	Foo     *clients_foo_foo.FooStruct
}
