// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  exception

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( BadRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BadRequest ) UnmarshalJSON([]byte) error { return nil }
func ( BadRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BadRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BadRequest *BadRequest

func ( NotAvailable ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NotAvailable ) UnmarshalJSON([]byte) error { return nil }
func ( NotAvailable ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NotAvailable ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NotAvailable *NotAvailable

func ( NotFound ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NotFound ) UnmarshalJSON([]byte) error { return nil }
func ( NotFound ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NotFound ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NotFound *NotFound

func ( PayloadLimited ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PayloadLimited ) UnmarshalJSON([]byte) error { return nil }
func ( PayloadLimited ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PayloadLimited ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PayloadLimited *PayloadLimited

func ( PermissionDenied ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PermissionDenied ) UnmarshalJSON([]byte) error { return nil }
func ( PermissionDenied ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PermissionDenied ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PermissionDenied *PermissionDenied

func ( RateLimited ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* RateLimited ) UnmarshalJSON([]byte) error { return nil }
func ( RateLimited ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* RateLimited ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RateLimited *RateLimited

func ( ServerError ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ServerError ) UnmarshalJSON([]byte) error { return nil }
func ( ServerError ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ServerError ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ServerError *ServerError

func ( TemporaryRedirect ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* TemporaryRedirect ) UnmarshalJSON([]byte) error { return nil }
func ( TemporaryRedirect ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* TemporaryRedirect ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_TemporaryRedirect *TemporaryRedirect

func ( Unauthenticated ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Unauthenticated ) UnmarshalJSON([]byte) error { return nil }
func ( Unauthenticated ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Unauthenticated ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Unauthenticated *Unauthenticated

func ( Unauthorized ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Unauthorized ) UnmarshalJSON([]byte) error { return nil }
func ( Unauthorized ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Unauthorized ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Unauthorized *Unauthorized

func ( UserBanned ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* UserBanned ) UnmarshalJSON([]byte) error { return nil }
func ( UserBanned ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* UserBanned ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UserBanned *UserBanned
