// Code generated by zanzibar
// @generated
// TODO: (lu) generate

package baz

import (
	"runtime"

	"github.com/uber/zanzibar/examples/example-gateway/build/gen-code/github.com/uber/zanzibar/endpoints/baz/baz"
	"github.com/uber/zanzibar/runtime"
)

func getDirName() string {
	_, file, _, _ := runtime.Caller(0)
	return zanzibar.GetDirnameFromRuntimeCaller(file)
}

// CallHTTPRequest is the http body type for endpoint call.
type CallHTTPRequest struct {
	Arg *baz.BazRequest
}
