package mocks

import mock "github.com/stretchr/testify/mock"
import thrift "github.com/uber/tchannel-go/thrift"

// TChanSecondService is an autogenerated mock type for the TChanSecondService type
type TChanSecondService struct {
	mock.Mock
}

// Echo provides a mock function with given fields: ctx, arg
func (_m *TChanSecondService) Echo(ctx thrift.Context, arg string) (string, error) {
	ret := _m.Called(ctx, arg)

	var r0 string
	if rf, ok := ret.Get(0).(func(thrift.Context, string) string); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(thrift.Context, string) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
