// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  googleNow

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( AddCredentialRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AddCredentialRequest ) UnmarshalJSON([]byte) error { return nil }
func ( AddCredentialRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AddCredentialRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AddCredentialRequest *AddCredentialRequest
