// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package googleNow

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB2ae1c62DecodeGithubComUberZanzibarExamplesExampleGatewayClientsGoogleNow(in *jlexer.Lexer, out *AddCredentialRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "authCode":
			out.AuthCode = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB2ae1c62EncodeGithubComUberZanzibarExamplesExampleGatewayClientsGoogleNow(out *jwriter.Writer, in AddCredentialRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"authCode\":")
	out.String(string(in.AuthCode))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AddCredentialRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB2ae1c62EncodeGithubComUberZanzibarExamplesExampleGatewayClientsGoogleNow(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AddCredentialRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB2ae1c62EncodeGithubComUberZanzibarExamplesExampleGatewayClientsGoogleNow(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AddCredentialRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB2ae1c62DecodeGithubComUberZanzibarExamplesExampleGatewayClientsGoogleNow(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AddCredentialRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB2ae1c62DecodeGithubComUberZanzibarExamplesExampleGatewayClientsGoogleNow(l, v)
}
