// Code generated by thriftrw v1.0.0
// @generated

package baz

import (
	"errors"
	"fmt"
	"go.uber.org/thriftrw/wire"
	"strings"
)

type SecondService_Echo_Args struct {
	Arg *string `json:"arg,omitempty"`
}

func (v *SecondService_Echo_Args) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Arg != nil {
		w, err = wire.NewValueString(*(v.Arg)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func (v *SecondService_Echo_Args) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 1:
			if field.Value.Type() == wire.TBinary {
				var x string
				x, err = field.Value.GetString(), error(nil)
				v.Arg = &x
				if err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func (v *SecondService_Echo_Args) String() string {
	var fields [1]string
	i := 0
	if v.Arg != nil {
		fields[i] = fmt.Sprintf("Arg: %v", *(v.Arg))
		i++
	}
	return fmt.Sprintf("SecondService_Echo_Args{%v}", strings.Join(fields[:i], ", "))
}

func (v *SecondService_Echo_Args) MethodName() string {
	return "Echo"
}

func (v *SecondService_Echo_Args) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

var SecondService_Echo_Helper = struct {
	Args           func(arg *string) *SecondService_Echo_Args
	IsException    func(error) bool
	WrapResponse   func(string, error) (*SecondService_Echo_Result, error)
	UnwrapResponse func(*SecondService_Echo_Result) (string, error)
}{}

func init() {
	SecondService_Echo_Helper.Args = func(arg *string) *SecondService_Echo_Args {
		return &SecondService_Echo_Args{Arg: arg}
	}
	SecondService_Echo_Helper.IsException = func(err error) bool {
		switch err.(type) {
		default:
			return false
		}
	}
	SecondService_Echo_Helper.WrapResponse = func(success string, err error) (*SecondService_Echo_Result, error) {
		if err == nil {
			return &SecondService_Echo_Result{Success: &success}, nil
		}
		return nil, err
	}
	SecondService_Echo_Helper.UnwrapResponse = func(result *SecondService_Echo_Result) (success string, err error) {
		if result.Success != nil {
			success = *result.Success
			return
		}
		err = errors.New("expected a non-void result")
		return
	}
}

type SecondService_Echo_Result struct {
	Success *string `json:"success,omitempty"`
}

func (v *SecondService_Echo_Result) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Success != nil {
		w, err = wire.NewValueString(*(v.Success)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 0, Value: w}
		i++
	}
	if i != 1 {
		return wire.Value{}, fmt.Errorf("SecondService_Echo_Result should have exactly one field: got %v fields", i)
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func (v *SecondService_Echo_Result) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 0:
			if field.Value.Type() == wire.TBinary {
				var x string
				x, err = field.Value.GetString(), error(nil)
				v.Success = &x
				if err != nil {
					return err
				}
			}
		}
	}
	count := 0
	if v.Success != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("SecondService_Echo_Result should have exactly one field: got %v fields", count)
	}
	return nil
}

func (v *SecondService_Echo_Result) String() string {
	var fields [1]string
	i := 0
	if v.Success != nil {
		fields[i] = fmt.Sprintf("Success: %v", *(v.Success))
		i++
	}
	return fmt.Sprintf("SecondService_Echo_Result{%v}", strings.Join(fields[:i], ", "))
}

func (v *SecondService_Echo_Result) MethodName() string {
	return "Echo"
}

func (v *SecondService_Echo_Result) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}
