// Code generated by thriftrw v1.0.0
// @generated

package baz

import (
	"errors"
	"fmt"
	"go.uber.org/thriftrw/wire"
	"strings"
)

type SimpleService_SimpleFuture_Args struct{}

func (v *SimpleService_SimpleFuture_Args) ToWire() (wire.Value, error) {
	var (
		fields [0]wire.Field
		i      int = 0
	)
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func (v *SimpleService_SimpleFuture_Args) FromWire(w wire.Value) error {
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		}
	}
	return nil
}

func (v *SimpleService_SimpleFuture_Args) String() string {
	var fields [0]string
	i := 0
	return fmt.Sprintf("SimpleService_SimpleFuture_Args{%v}", strings.Join(fields[:i], ", "))
}

func (v *SimpleService_SimpleFuture_Args) MethodName() string {
	return "SimpleFuture"
}

func (v *SimpleService_SimpleFuture_Args) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

var SimpleService_SimpleFuture_Helper = struct {
	Args           func() *SimpleService_SimpleFuture_Args
	IsException    func(error) bool
	WrapResponse   func(error) (*SimpleService_SimpleFuture_Result, error)
	UnwrapResponse func(*SimpleService_SimpleFuture_Result) error
}{}

func init() {
	SimpleService_SimpleFuture_Helper.Args = func() *SimpleService_SimpleFuture_Args {
		return &SimpleService_SimpleFuture_Args{}
	}
	SimpleService_SimpleFuture_Helper.IsException = func(err error) bool {
		switch err.(type) {
		case *SimpleErr:
			return true
		case *NewErr:
			return true
		default:
			return false
		}
	}
	SimpleService_SimpleFuture_Helper.WrapResponse = func(err error) (*SimpleService_SimpleFuture_Result, error) {
		if err == nil {
			return &SimpleService_SimpleFuture_Result{}, nil
		}
		switch e := err.(type) {
		case *SimpleErr:
			if e == nil {
				return nil, errors.New("WrapResponse received non-nil error type with nil value for SimpleService_SimpleFuture_Result.SimpleErr")
			}
			return &SimpleService_SimpleFuture_Result{SimpleErr: e}, nil
		case *NewErr:
			if e == nil {
				return nil, errors.New("WrapResponse received non-nil error type with nil value for SimpleService_SimpleFuture_Result.NewErr")
			}
			return &SimpleService_SimpleFuture_Result{NewErr: e}, nil
		}
		return nil, err
	}
	SimpleService_SimpleFuture_Helper.UnwrapResponse = func(result *SimpleService_SimpleFuture_Result) (err error) {
		if result.SimpleErr != nil {
			err = result.SimpleErr
			return
		}
		if result.NewErr != nil {
			err = result.NewErr
			return
		}
		return
	}
}

type SimpleService_SimpleFuture_Result struct {
	SimpleErr *SimpleErr `json:"simpleErr,omitempty"`
	NewErr    *NewErr    `json:"newErr,omitempty"`
}

func (v *SimpleService_SimpleFuture_Result) ToWire() (wire.Value, error) {
	var (
		fields [2]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.SimpleErr != nil {
		w, err = v.SimpleErr.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}
	if v.NewErr != nil {
		w, err = v.NewErr.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 2, Value: w}
		i++
	}
	if i > 1 {
		return wire.Value{}, fmt.Errorf("SimpleService_SimpleFuture_Result should have at most one field: got %v fields", i)
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _NewErr_Read(w wire.Value) (*NewErr, error) {
	var v NewErr
	err := v.FromWire(w)
	return &v, err
}

func (v *SimpleService_SimpleFuture_Result) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 1:
			if field.Value.Type() == wire.TStruct {
				v.SimpleErr, err = _SimpleErr_Read(field.Value)
				if err != nil {
					return err
				}
			}
		case 2:
			if field.Value.Type() == wire.TStruct {
				v.NewErr, err = _NewErr_Read(field.Value)
				if err != nil {
					return err
				}
			}
		}
	}
	count := 0
	if v.SimpleErr != nil {
		count++
	}
	if v.NewErr != nil {
		count++
	}
	if count > 1 {
		return fmt.Errorf("SimpleService_SimpleFuture_Result should have at most one field: got %v fields", count)
	}
	return nil
}

func (v *SimpleService_SimpleFuture_Result) String() string {
	var fields [2]string
	i := 0
	if v.SimpleErr != nil {
		fields[i] = fmt.Sprintf("SimpleErr: %v", v.SimpleErr)
		i++
	}
	if v.NewErr != nil {
		fields[i] = fmt.Sprintf("NewErr: %v", v.NewErr)
		i++
	}
	return fmt.Sprintf("SimpleService_SimpleFuture_Result{%v}", strings.Join(fields[:i], ", "))
}

func (v *SimpleService_SimpleFuture_Result) MethodName() string {
	return "SimpleFuture"
}

func (v *SimpleService_SimpleFuture_Result) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}
