// Code generated by thriftrw v1.0.0
// @generated

package baz

import "go.uber.org/thriftrw/version"

func init() {
	version.CheckCompatWithGeneratedCodeAt("1.0.0", "github.com/uber/zanzibar/test/runtime/tchannel/gen-code/baz")
}
