// Code generated by thriftrw v1.0.0
// @generated

package meta

import (
	"errors"
	"fmt"
	"go.uber.org/thriftrw/wire"
	"strings"
)

type Meta_VersionInfo_Args struct{}

func (v *Meta_VersionInfo_Args) ToWire() (wire.Value, error) {
	var (
		fields [0]wire.Field
		i      int = 0
	)
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func (v *Meta_VersionInfo_Args) FromWire(w wire.Value) error {
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		}
	}
	return nil
}

func (v *Meta_VersionInfo_Args) String() string {
	var fields [0]string
	i := 0
	return fmt.Sprintf("Meta_VersionInfo_Args{%v}", strings.Join(fields[:i], ", "))
}

func (v *Meta_VersionInfo_Args) MethodName() string {
	return "versionInfo"
}

func (v *Meta_VersionInfo_Args) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

var Meta_VersionInfo_Helper = struct {
	Args           func() *Meta_VersionInfo_Args
	IsException    func(error) bool
	WrapResponse   func(*VersionInfo, error) (*Meta_VersionInfo_Result, error)
	UnwrapResponse func(*Meta_VersionInfo_Result) (*VersionInfo, error)
}{}

func init() {
	Meta_VersionInfo_Helper.Args = func() *Meta_VersionInfo_Args {
		return &Meta_VersionInfo_Args{}
	}
	Meta_VersionInfo_Helper.IsException = func(err error) bool {
		switch err.(type) {
		default:
			return false
		}
	}
	Meta_VersionInfo_Helper.WrapResponse = func(success *VersionInfo, err error) (*Meta_VersionInfo_Result, error) {
		if err == nil {
			return &Meta_VersionInfo_Result{Success: success}, nil
		}
		return nil, err
	}
	Meta_VersionInfo_Helper.UnwrapResponse = func(result *Meta_VersionInfo_Result) (success *VersionInfo, err error) {
		if result.Success != nil {
			success = result.Success
			return
		}
		err = errors.New("expected a non-void result")
		return
	}
}

type Meta_VersionInfo_Result struct {
	Success *VersionInfo `json:"success,omitempty"`
}

func (v *Meta_VersionInfo_Result) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Success != nil {
		w, err = v.Success.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 0, Value: w}
		i++
	}
	if i != 1 {
		return wire.Value{}, fmt.Errorf("Meta_VersionInfo_Result should have exactly one field: got %v fields", i)
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _VersionInfo_Read(w wire.Value) (*VersionInfo, error) {
	var v VersionInfo
	err := v.FromWire(w)
	return &v, err
}

func (v *Meta_VersionInfo_Result) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 0:
			if field.Value.Type() == wire.TStruct {
				v.Success, err = _VersionInfo_Read(field.Value)
				if err != nil {
					return err
				}
			}
		}
	}
	count := 0
	if v.Success != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("Meta_VersionInfo_Result should have exactly one field: got %v fields", count)
	}
	return nil
}

func (v *Meta_VersionInfo_Result) String() string {
	var fields [1]string
	i := 0
	if v.Success != nil {
		fields[i] = fmt.Sprintf("Success: %v", v.Success)
		i++
	}
	return fmt.Sprintf("Meta_VersionInfo_Result{%v}", strings.Join(fields[:i], ", "))
}

func (v *Meta_VersionInfo_Result) MethodName() string {
	return "versionInfo"
}

func (v *Meta_VersionInfo_Result) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}
