// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  contacts

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( ContactFragment ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ContactFragment ) UnmarshalJSON([]byte) error { return nil }
func ( ContactFragment ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ContactFragment ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ContactFragment *ContactFragment

func ( ContactAttributes ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ContactAttributes ) UnmarshalJSON([]byte) error { return nil }
func ( ContactAttributes ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ContactAttributes ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ContactAttributes *ContactAttributes

func ( Contact ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Contact ) UnmarshalJSON([]byte) error { return nil }
func ( Contact ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Contact ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Contact *Contact

func ( SaveContactsRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SaveContactsRequest ) UnmarshalJSON([]byte) error { return nil }
func ( SaveContactsRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SaveContactsRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SaveContactsRequest *SaveContactsRequest
