name: echo
type: grpc
config:
  idlFile: clients/echo/echo.proto
  exposedMethods:
    "EchoEcho": "Echo::Echo"
  fixture:
    importPath: github.com/uber/zanzibar/examples/selective-gateway/clients/echo/fixture
    scenarios:
      EchoEcho:
      - success
CustomInitialisation: true
