name: Build using GitHub Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.16']
        node-version: ['v8.12.0']  # version Travis was using
    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
      GO111MODULE: off
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    steps:
            
      - name: checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
      
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # install deps
      - run: sudo apt-get -qq update
      - run: sudo apt-get install -qq time
      - run: sudo apt-get install -qq build-essential libssl-dev git unzip
      - run: sudo apt-get install -qq libluajit-5.1-2 libluajit-5.1-common
      
      # install wrk
      # they need to be on a single line otherwise `working-directory` directive will change the working path.
      - run: git clone https://github.com/wg/wrk.git wrk && cd wrk && make && sudo cp -r wrk /usr/local/bin
      
      # install protoc
      - run: curl -0L -O https://github.com/google/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip
      - run: sudo unzip -o protoc-3.7.1-linux-x86_64.zip -d /usr/local bin/protoc
      - run: rm -f protoc-3.7.1-linux-x86_64.zip

      - name: make jenkins-install
        run: make jenkins-install
        
      - name: make jenkins-test
        run: make jenkins-test
        
      - name: make install
        run: make install
        
      - name: make fast-bench
        run: make fast-bench
        
      - name: make bins
        run: make bins

      - name: make test-benchmark-runner
        run: make test-benchmark-runner
   
      - name: make cover
        run: make cover
        
      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}/coverage/lcov.info
        
      - run: echo "🍏 This job's status is ${{ job.status }}."
