name: Build using GitHub Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.15', '1.16']
        node-version: ['0.10.32']
    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
      GO111MODULE: off
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    steps:
            
      - name: checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
      
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: make jenkins-install
        run: make jenkins-install
        shell: bash
        
      - name: make jenkins-test
        run: make jenkins-test
        
      - name: make install
        run: make install
        
      - name: make cover
        run: make cover
        
      - name: make fast-bench
        run: make fast-bench
        
      - name: make bins
        run: make bins
        
      - name: make test-benchmark-runner
        run: make test-benchmark-runner
        
      - run: echo "🍏 This job's status is ${{ job.status }}."
