// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/uber/zanzibar/repository (interfaces: Fetcher)

package mock_repository

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Fetcher interface
type MockFetcher struct {
	ctrl     *gomock.Controller
	recorder *_MockFetcherRecorder
}

// Recorder for MockFetcher (not exported)
type _MockFetcherRecorder struct {
	mock *MockFetcher
}

func NewMockFetcher(ctrl *gomock.Controller) *MockFetcher {
	mock := &MockFetcher{ctrl: ctrl}
	mock.recorder = &_MockFetcherRecorder{mock}
	return mock
}

func (_m *MockFetcher) EXPECT() *_MockFetcherRecorder {
	return _m.recorder
}

func (_m *MockFetcher) Clone(_param0 string, _param1 string) (string, error) {
	ret := _m.ctrl.Call(_m, "Clone", _param0, _param1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockFetcherRecorder) Clone(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Clone", arg0, arg1)
}

func (_m *MockFetcher) Update(_param0 string, _param1 string) (bool, error) {
	ret := _m.ctrl.Call(_m, "Update", _param0, _param1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockFetcherRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Update", arg0, arg1)
}

func (_m *MockFetcher) Version(_param0 string) (string, error) {
	ret := _m.ctrl.Call(_m, "Version", _param0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockFetcherRecorder) Version(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Version", arg0)
}
