config:
  endpoints:
  - ./add_credentials.yaml
  - ./check_credentials.yaml
  rateLimit: 100
dependencies:
  adapter:
  - test_adapter1
  - test_adapter2
  client:
  - google-now
name: googlenow
type: http
