// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  foo

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( FooName ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* FooName ) UnmarshalJSON([]byte) error { return nil }
func ( FooName ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* FooName ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_FooName *FooName

func ( FooStruct ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* FooStruct ) UnmarshalJSON([]byte) error { return nil }
func ( FooStruct ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* FooStruct ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_FooStruct *FooStruct
